// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UPS.WWRR.Data.Models;

#nullable disable

namespace UPS.WWRR.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251126144710_Add-TASYBRL-Table")]
    partial class AddTASYBRLTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UPS.WWRR.Data.Models.AccessorialException", b =>
                {
                    b.Property<string>("BusinessRuleTypeCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("brl_typ_cd");

                    b.Property<string>("OriginGpuExportCountry")
                        .HasMaxLength(4)
                        .HasColumnType("char")
                        .HasColumnName("gpn_xpt_cny_cd");

                    b.Property<string>("DestinationGpuImportCountry")
                        .HasMaxLength(4)
                        .HasColumnType("char")
                        .HasColumnName("gpn_ipt_cny_cd");

                    b.Property<string>("PackageType")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("pkg_cha_typ_cd");

                    b.Property<string>("BillTerm")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("bil_ter_typ_cd");

                    b.Property<string>("ServiceFeatureTypeCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("svc_fea_typ_cd");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("svc_typ_cd");

                    b.Property<string>("MovementDirectionCode")
                        .HasMaxLength(1)
                        .HasColumnType("char")
                        .HasColumnName("mvm_drc_cd");

                    b.Property<string>("CustomerRateType")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("cus_csf_typ_cd");

                    b.Property<string>("AccessorialCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("asy_svc_typ_cd");

                    b.Property<string>("ApprovalStatusCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("apv_sts_cd");

                    b.Property<DateTime>("RecordEffectiveStartDate")
                        .HasColumnType("Date")
                        .HasColumnName("rec_eff_stt_dt");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.Property<DateTime>("RecordEffectiveEndDate")
                        .HasColumnType("Date")
                        .HasColumnName("rec_eff_end_dt");

                    b.HasKey("BusinessRuleTypeCode", "OriginGpuExportCountry", "DestinationGpuImportCountry", "PackageType", "BillTerm", "ServiceFeatureTypeCode", "ServiceType", "MovementDirectionCode", "CustomerRateType", "AccessorialCode", "ApprovalStatusCode", "RecordEffectiveStartDate");

                    b.ToTable("tasybrl");
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.AccessorialExceptionStaging", b =>
                {
                    b.Property<string>("BusinessRuleTypeCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("brl_typ_cd");

                    b.Property<string>("OriginGpuExportCountry")
                        .HasMaxLength(4)
                        .HasColumnType("char")
                        .HasColumnName("gpn_xpt_cny_cd");

                    b.Property<string>("DestinationGpuImportCountry")
                        .HasMaxLength(4)
                        .HasColumnType("char")
                        .HasColumnName("gpn_ipt_cny_cd");

                    b.Property<string>("PackageType")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("pkg_cha_typ_cd");

                    b.Property<string>("BillTerm")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("bil_ter_typ_cd");

                    b.Property<string>("ServiceFeatureTypeCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("svc_fea_typ_cd");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("svc_typ_cd");

                    b.Property<string>("MovementDirectionCode")
                        .HasMaxLength(1)
                        .HasColumnType("char")
                        .HasColumnName("mvm_drc_cd");

                    b.Property<string>("CustomerRateType")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("cus_csf_typ_cd");

                    b.Property<string>("AccessorialCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("asy_svc_typ_cd");

                    b.Property<string>("ApprovalStatusCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("apv_sts_cd");

                    b.Property<DateTime>("RecordEffectiveStartDate")
                        .HasColumnType("Date")
                        .HasColumnName("rec_eff_stt_dt");

                    b.Property<short>("IsCompletedIndicator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("is_completed_ir");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.Property<DateTime>("RecordEffectiveEndDate")
                        .HasColumnType("Date")
                        .HasColumnName("rec_eff_end_dt");

                    b.HasKey("BusinessRuleTypeCode", "OriginGpuExportCountry", "DestinationGpuImportCountry", "PackageType", "BillTerm", "ServiceFeatureTypeCode", "ServiceType", "MovementDirectionCode", "CustomerRateType", "AccessorialCode", "ApprovalStatusCode", "RecordEffectiveStartDate");

                    b.ToTable("tasybrl_stg", (string)null);
                });

#pragma warning restore 612, 618
        }
    }
}
