// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UPS.WWRR.Data.Models;

#nullable disable

namespace UPS.WWRR.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251208105355_Add-TCZMSYS-table")]
    partial class AddTCZMSYStable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UPS.WWRR.Data.Models.AccessorialException", b =>
                {
                    b.Property<string>("BusinessRuleTypeCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("brl_typ_cd");

                    b.Property<string>("OriginGpuExportCountry")
                        .HasMaxLength(4)
                        .HasColumnType("char")
                        .HasColumnName("gpn_xpt_cny_cd");

                    b.Property<string>("DestinationGpuImportCountry")
                        .HasMaxLength(4)
                        .HasColumnType("char")
                        .HasColumnName("gpn_ipt_cny_cd");

                    b.Property<string>("PackageType")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("pkg_cha_typ_cd");

                    b.Property<string>("BillTerm")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("bil_ter_typ_cd");

                    b.Property<string>("ServiceFeatureTypeCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("svc_fea_typ_cd");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("svc_typ_cd");

                    b.Property<string>("MovementDirectionCode")
                        .HasMaxLength(1)
                        .HasColumnType("char")
                        .HasColumnName("mvm_drc_cd");

                    b.Property<string>("CustomerRateType")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("cus_csf_typ_cd");

                    b.Property<string>("AccessorialCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("asy_svc_typ_cd");

                    b.Property<string>("ApprovalStatusCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("apv_sts_cd");

                    b.Property<DateTime>("RecordEffectiveStartDate")
                        .HasColumnType("Date")
                        .HasColumnName("rec_eff_stt_dt");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.Property<DateTime>("RecordEffectiveEndDate")
                        .HasColumnType("Date")
                        .HasColumnName("rec_eff_end_dt");

                    b.HasKey("BusinessRuleTypeCode", "OriginGpuExportCountry", "DestinationGpuImportCountry", "PackageType", "BillTerm", "ServiceFeatureTypeCode", "ServiceType", "MovementDirectionCode", "CustomerRateType", "AccessorialCode", "ApprovalStatusCode", "RecordEffectiveStartDate");

                    b.ToTable("tasybrl");
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.AccessorialExceptionStaging", b =>
                {
                    b.Property<string>("BusinessRuleTypeCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("brl_typ_cd");

                    b.Property<string>("OriginGpuExportCountry")
                        .HasMaxLength(4)
                        .HasColumnType("char")
                        .HasColumnName("gpn_xpt_cny_cd");

                    b.Property<string>("DestinationGpuImportCountry")
                        .HasMaxLength(4)
                        .HasColumnType("char")
                        .HasColumnName("gpn_ipt_cny_cd");

                    b.Property<string>("PackageType")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("pkg_cha_typ_cd");

                    b.Property<string>("BillTerm")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("bil_ter_typ_cd");

                    b.Property<string>("ServiceFeatureTypeCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("svc_fea_typ_cd");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("svc_typ_cd");

                    b.Property<string>("MovementDirectionCode")
                        .HasMaxLength(1)
                        .HasColumnType("char")
                        .HasColumnName("mvm_drc_cd");

                    b.Property<string>("CustomerRateType")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("cus_csf_typ_cd");

                    b.Property<string>("AccessorialCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("asy_svc_typ_cd");

                    b.Property<string>("ApprovalStatusCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("apv_sts_cd");

                    b.Property<DateTime>("RecordEffectiveStartDate")
                        .HasColumnType("Date")
                        .HasColumnName("rec_eff_stt_dt");

                    b.Property<short>("IsCompletedIndicator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("is_completed_ir");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.Property<DateTime>("RecordEffectiveEndDate")
                        .HasColumnType("Date")
                        .HasColumnName("rec_eff_end_dt");

                    b.HasKey("BusinessRuleTypeCode", "OriginGpuExportCountry", "DestinationGpuImportCountry", "PackageType", "BillTerm", "ServiceFeatureTypeCode", "ServiceType", "MovementDirectionCode", "CustomerRateType", "AccessorialCode", "ApprovalStatusCode", "RecordEffectiveStartDate");

                    b.ToTable("tasybrl_stg", (string)null);
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.AccessorialMinMaxCriteria", b =>
                {
                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("cny_cd");

                    b.Property<string>("AccessorialCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("asy_svc_typ_cd");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("ccy_cd");

                    b.Property<string>("AccessorialThresholdType")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("asy_trh_typ_cd");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("rec_eff_stt_dt");

                    b.Property<string>("StatusCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("svc_ra_cht_sts_cd");

                    b.Property<decimal>("AccessorialThreshold")
                        .HasColumnType("decimal(17,4)")
                        .HasColumnName("asy_trh_a");

                    b.Property<string>("CalculationMethod")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("ccl_mth_typ_cd");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("rec_eff_end_dt");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.HasKey("Country", "AccessorialCode", "Currency", "AccessorialThresholdType", "EffectiveDate", "StatusCode");

                    b.ToTable("tasytrh");
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.AccessorialMinMaxCriteriaStaging", b =>
                {
                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("cny_cd");

                    b.Property<string>("AccessorialCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("asy_svc_typ_cd");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("ccy_cd");

                    b.Property<string>("AccessorialThresholdType")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("asy_trh_typ_cd");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("rec_eff_stt_dt");

                    b.Property<string>("StatusCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("svc_ra_cht_sts_cd");

                    b.Property<decimal>("AccessorialThreshold")
                        .HasColumnType("decimal(17,4)")
                        .HasColumnName("asy_trh_a");

                    b.Property<string>("CalculationMethod")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("ccl_mth_typ_cd");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("rec_eff_end_dt");

                    b.Property<short>("IsCompletedIndicator")
                        .HasColumnType("smallint")
                        .HasColumnName("is_completed_ir");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.HasKey("Country", "AccessorialCode", "Currency", "AccessorialThresholdType", "EffectiveDate", "StatusCode");

                    b.ToTable("tasytrh_stg");
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.AccessorialThreshold", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("cny_cd");

                    b.Property<string>("AccessorialServiceTypeCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("asy_svc_typ_cd");

                    b.Property<string>("ApprovalStatusCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("apv_sts_cd");

                    b.Property<DateTime>("RecordEffectiveStartDate")
                        .HasColumnType("date")
                        .HasColumnName("rec_eff_stt_dt");

                    b.Property<int>("DailyThresholdQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("asy_dly_trh_qy");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.Property<DateTime>("RecordEffectiveEndDate")
                        .HasColumnType("date")
                        .HasColumnName("rec_eff_end_dt");

                    b.Property<int>("WeeklyThresholdQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("asy_wky_trh_qy");

                    b.HasKey("CountryCode", "AccessorialServiceTypeCode", "ApprovalStatusCode", "RecordEffectiveStartDate");

                    b.ToTable("tfputrh");
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.AccessorialThresholdStaging", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("cny_cd");

                    b.Property<string>("AccessorialServiceTypeCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("asy_svc_typ_cd");

                    b.Property<string>("ApprovalStatusCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("apv_sts_cd");

                    b.Property<DateTime>("RecordEffectiveStartDate")
                        .HasColumnType("date")
                        .HasColumnName("rec_eff_stt_dt");

                    b.Property<int>("DailyThresholdQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("asy_dly_trh_qy");

                    b.Property<short>("IsCompletedIndicator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("is_completed_ir");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.Property<DateTime>("RecordEffectiveEndDate")
                        .HasColumnType("date")
                        .HasColumnName("rec_eff_end_dt");

                    b.Property<int>("WeeklyThresholdQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("asy_wky_trh_qy");

                    b.HasKey("CountryCode", "AccessorialServiceTypeCode", "ApprovalStatusCode", "RecordEffectiveStartDate");

                    b.ToTable("tfputrh_stg", (string)null);
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.AlternateCurrency", b =>
                {
                    b.Property<string>("CurrencyFrom")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("cnv_fr_ccy_cd");

                    b.Property<string>("CurrencyTo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("cnv_to_ccy_cd");

                    b.Property<decimal>("DomesticCalculationQuantity")
                        .HasColumnType("decimal(9,0)")
                        .HasColumnName("alt_ccy_dmc_ccl_qy");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("Date")
                        .HasColumnName("alt_ccy_xch_stt_dt");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("Date")
                        .HasColumnName("alt_ccy_xch_end_dt");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(15,9)")
                        .HasColumnName("alt_ccy_xch_ra_qy");

                    b.Property<string>("ExportCountry")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("xpt_cny_cd");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.Property<decimal>("OriginalQuantity")
                        .HasColumnType("decimal(15,9)")
                        .HasColumnName("alt_ccy_xch_or_qy");

                    b.Property<decimal>("RoundedDomesticQuantity")
                        .HasColumnType("decimal(9,0)")
                        .HasColumnName("alt_ccy_rou_dmc_qy");

                    b.Property<string>("UserNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("char")
                        .HasDefaultValue("")
                        .HasColumnName("usr_nr");

                    b.ToTable("taltccy", (string)null);
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.AlternateCurrencyStaging", b =>
                {
                    b.Property<string>("CurrencyFrom")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("cnv_fr_ccy_cd");

                    b.Property<string>("CurrencyTo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("cnv_to_ccy_cd");

                    b.Property<decimal>("DomesticCalculationQuantity")
                        .HasColumnType("decimal(9,0)")
                        .HasColumnName("alt_ccy_dmc_ccl_qy");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("Date")
                        .HasColumnName("alt_ccy_xch_stt_dt");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("Date")
                        .HasColumnName("alt_ccy_xch_end_dt");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(15,9)")
                        .HasColumnName("alt_ccy_xch_ra_qy");

                    b.Property<string>("ExportCountry")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("xpt_cny_cd");

                    b.Property<short>("IsCompletedIndicator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("is_completed_ir");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.Property<decimal>("OriginalQuantity")
                        .HasColumnType("decimal(15,9)")
                        .HasColumnName("alt_ccy_xch_or_qy");

                    b.Property<decimal>("RoundedDomesticQuantity")
                        .HasColumnType("decimal(9,0)")
                        .HasColumnName("alt_ccy_rou_dmc_qy");

                    b.Property<string>("UserNumber")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("char")
                        .HasDefaultValue("")
                        .HasColumnName("usr_nr");

                    b.ToTable("taltccy_stg", (string)null);
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.AreaClassificationDetail", b =>
                {
                    b.Property<int>("ChartNumber")
                        .HasColumnType("integer")
                        .HasColumnName("zch_nr");

                    b.Property<DateTime>("ChartEffectiveDate")
                        .HasColumnType("Date")
                        .HasColumnName("ara_csf_hdr_stt_dt");

                    b.Property<DateTime>("ChartEndDate")
                        .HasColumnType("Date")
                        .HasColumnName("ara_csf_dtl_end_dt");

                    b.Property<string>("OriginCountry")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("org_cny_cd");

                    b.Property<string>("DestinationCountry")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("dtn_cny_cd");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("svc_typ_cd");

                    b.Property<string>("AreaClassificationRule")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("ara_csf_dtl_rul_cd");

                    b.Property<string>("OriginPolticialDivision2")
                        .HasMaxLength(50)
                        .HasColumnType("char")
                        .HasColumnName("org_pol_div_2_na");

                    b.Property<string>("DestinationPoliticalDivision2")
                        .HasMaxLength(50)
                        .HasColumnType("char")
                        .HasColumnName("dtn_pol_div_2_na");

                    b.Property<string>("OriginLowPostal")
                        .HasMaxLength(9)
                        .HasColumnType("char")
                        .HasColumnName("org_rng_lo_psl_cd");

                    b.Property<string>("OriginHighPostal")
                        .HasMaxLength(9)
                        .HasColumnType("char")
                        .HasColumnName("org_rng_hi_psl_cd");

                    b.Property<string>("DestinationLowPostal")
                        .HasMaxLength(9)
                        .HasColumnType("char")
                        .HasColumnName("dtn_rng_lo_psl_cd");

                    b.Property<string>("DestinationHighPostal")
                        .HasMaxLength(9)
                        .HasColumnType("char")
                        .HasColumnName("dtn_rng_hi_psl_cd");

                    b.Property<string>("StatusCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("bus_eny_acs_sts_cd");

                    b.Property<string>("AreaClassificationMnt")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("ara_csf_dtl_mnt_cd");

                    b.Property<string>("ChargeClassification")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("ra_chg_csf_typ_cd");

                    b.Property<string>("DestinationGeographicArea")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("dtn_geo_ara_typ_cd");

                    b.Property<string>("DestinationPoliticalDivision1")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("char")
                        .HasColumnName("dtn_pol_div_1_cd");

                    b.Property<string>("GeopoliticalDestinationCountry")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("char")
                        .HasColumnName("dtn_gpu_nr");

                    b.Property<string>("GeopoliticalOriginCountry")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("char")
                        .HasColumnName("org_gpu_nr");

                    b.Property<string>("OriginGeographicArea")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("org_geo_ara_typ_cd");

                    b.Property<string>("OriginPolticialDivision1")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("char")
                        .HasColumnName("org_pol_div_1_cd");

                    b.HasKey("ChartNumber", "ChartEffectiveDate", "ChartEndDate", "OriginCountry", "DestinationCountry", "ServiceType", "AreaClassificationRule", "OriginPolticialDivision2", "DestinationPoliticalDivision2", "OriginLowPostal", "OriginHighPostal", "DestinationLowPostal", "DestinationHighPostal", "StatusCode");

                    b.ToTable("tarcldt");
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.AreaClassificationHeader", b =>
                {
                    b.Property<string>("OriginCountry")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("org_cny_cd");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("svc_typ_cd");

                    b.Property<string>("AccessorialCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("asy_svc_typ_cd");

                    b.Property<string>("DestinationCountry")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("dtn_cny_cd");

                    b.Property<int>("ChartNumber")
                        .HasColumnType("integer")
                        .HasColumnName("zch_nr");

                    b.Property<DateTime>("ChartEffectiveDate")
                        .HasColumnType("Date")
                        .HasColumnName("ara_csf_hdr_stt_dt");

                    b.Property<DateTime>("ChartEndDate")
                        .HasColumnType("Date")
                        .HasColumnName("ara_csf_hdr_end_dt");

                    b.Property<string>("StatusCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("bus_eny_acs_sts_cd");

                    b.Property<string>("GeopoliticalDestinationCountry")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("char")
                        .HasColumnName("dtn_gpu_nr");

                    b.Property<string>("GeopoliticalOriginCountry")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("char")
                        .HasColumnName("org_gpu_nr");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("char")
                        .HasColumnName("zch_lg_dsc_te");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("char")
                        .HasColumnName("zch_sht_dsc_te");

                    b.HasKey("OriginCountry", "ServiceType", "AccessorialCode", "DestinationCountry", "ChartNumber", "ChartEffectiveDate", "ChartEndDate", "StatusCode");

                    b.ToTable("tarclhd");
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.BmaCapAmount", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(4)
                        .HasColumnType("char")
                        .HasColumnName("gpn_cd");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("svc_typ_cd");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("Date")
                        .HasColumnName("rec_eff_stt_dt");

                    b.Property<string>("StatusCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("svc_ra_cht_sts_cd");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("Date")
                        .HasColumnName("rec_eff_end_dt");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.Property<decimal>("MaximumIncentive")
                        .HasColumnType("decimal(7,4)")
                        .HasColumnName("max_ncv_pr");

                    b.Property<string>("UpsOfferProgramCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("ups_ofr_pgm_cd");

                    b.HasKey("CountryCode", "ServiceType", "EffectiveDate", "StatusCode");

                    b.ToTable("tbmavcs");
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.BmaCapAmountStaging", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(4)
                        .HasColumnType("char")
                        .HasColumnName("gpn_cd");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("svc_typ_cd");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("Date")
                        .HasColumnName("rec_eff_stt_dt");

                    b.Property<string>("StatusCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("svc_ra_cht_sts_cd");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("Date")
                        .HasColumnName("rec_eff_end_dt");

                    b.Property<short>("IsCompletedIndicator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("is_completed_ir");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.Property<decimal>("MaximumIncentive")
                        .HasColumnType("decimal(7,4)")
                        .HasColumnName("max_ncv_pr");

                    b.Property<string>("UpsOfferProgramCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("ups_ofr_pgm_cd");

                    b.HasKey("CountryCode", "ServiceType", "EffectiveDate", "StatusCode");

                    b.ToTable("tbmavcs_stg", (string)null);
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.CzmSystemRules", b =>
                {
                    b.Property<string>("CommandTableTypeCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("cd_tbl_typ_cd");

                    b.Property<string>("CommandTableCode")
                        .HasMaxLength(20)
                        .HasColumnType("char")
                        .HasColumnName("cd_tbl_cd");

                    b.Property<DateTime>("TableStartDate")
                        .HasColumnType("Date")
                        .HasColumnName("cd_tbl_stt_dt");

                    b.Property<DateTime>("TableEndDate")
                        .HasColumnType("Date")
                        .HasColumnName("cd_tbl_end_dt");

                    b.Property<string>("ApprovalStatusCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("apv_sts_cd");

                    b.Property<string>("DecodeCodeDescription")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("char")
                        .HasColumnName("dco_cd_dsc_te");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.HasKey("CommandTableTypeCode", "CommandTableCode", "TableStartDate", "TableEndDate", "ApprovalStatusCode");

                    b.ToTable("tczmsys");
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.CzmSystemRulesStaging", b =>
                {
                    b.Property<string>("CommandTableTypeCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("cd_tbl_typ_cd");

                    b.Property<string>("CommandTableCode")
                        .HasMaxLength(20)
                        .HasColumnType("char")
                        .HasColumnName("cd_tbl_cd");

                    b.Property<DateTime>("TableStartDate")
                        .HasColumnType("Date")
                        .HasColumnName("cd_tbl_stt_dt");

                    b.Property<DateTime>("TableEndDate")
                        .HasColumnType("Date")
                        .HasColumnName("cd_tbl_end_dt");

                    b.Property<string>("ApprovalStatusCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("apv_sts_cd");

                    b.Property<string>("DecodeCodeDescription")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("char")
                        .HasColumnName("dco_cd_dsc_te");

                    b.Property<short>("IsCompletedIndicator")
                        .HasColumnType("smallint")
                        .HasColumnName("is_completed_ir");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.HasKey("CommandTableTypeCode", "CommandTableCode", "TableStartDate", "TableEndDate", "ApprovalStatusCode");

                    b.ToTable("tczmsys_stg");
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.DataLoad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq_nr");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BatchSize")
                        .HasColumnType("integer")
                        .HasColumnName("batch_size");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("create_udt_ts");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("data_source");

                    b.Property<string>("FileLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_location");

                    b.Property<string>("LoadStatusCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("load_sts_cd");

                    b.Property<string>("LoadTableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("load_table_na");

                    b.Property<long>("LoadVersionNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("load_ver_nr");

                    b.Property<string>("LogFileLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("log_file_location");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_udt_ts");

                    b.Property<int>("TotalBatchNumber")
                        .HasColumnType("integer")
                        .HasColumnName("total_batch_nr");

                    b.HasKey("Id");

                    b.ToTable("data_loads");
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.DataLoadDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq_nr");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BatchNumber")
                        .HasColumnType("integer")
                        .HasColumnName("batch_nr");

                    b.Property<long>("DataLoadId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_load_seq_nr");

                    b.Property<string>("DataLoadType")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("data_load_typ");

                    b.Property<short>("ErrorIndicator")
                        .HasColumnType("smallint")
                        .HasColumnName("err_ir");

                    b.Property<int>("RecordsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("rec_del_nr");

                    b.Property<int>("RecordsInserted")
                        .HasColumnType("integer")
                        .HasColumnName("rec_ins_nr");

                    b.Property<int>("RecordsUpdated")
                        .HasColumnType("integer")
                        .HasColumnName("rec_upd_nr");

                    b.Property<string>("TimePeriodTypeCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("tm_prd_typ_cd");

                    b.Property<int>("TimeProcessValue")
                        .HasColumnType("integer")
                        .HasColumnName("tm_prc_val");

                    b.HasKey("Id");

                    b.HasIndex("DataLoadId");

                    b.ToTable("data_load_details");
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.DataLoadError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq_nr");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("create_udt_ts");

                    b.Property<long>("DataLoadDetailId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_load_detail_seq_nr");

                    b.Property<int>("ErrorCode")
                        .HasColumnType("integer")
                        .HasColumnName("err_cd");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("err_msg_te");

                    b.Property<string>("ErrorStoredProcedureName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("err_sp_na");

                    b.HasKey("Id");

                    b.HasIndex("DataLoadDetailId");

                    b.ToTable("data_load_errors");
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.DataLoadException", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq_nr");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("create_udt_ts");

                    b.Property<long>("DataLoadDetailId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_load_detail_seq_nr");

                    b.Property<string>("ErrorFieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("err_fld_na");

                    b.Property<string>("ErrorFieldValue")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("err_fld_str");

                    b.Property<string>("TableKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("table_key_str");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("table_na");

                    b.HasKey("Id");

                    b.HasIndex("DataLoadDetailId");

                    b.ToTable("data_load_exceptions");
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.DeficitWeightThreshold", b =>
                {
                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("cny_cd");

                    b.Property<string>("WeightMeasurementUnitType")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("wgt_ms_unt_typ_cd");

                    b.Property<string>("ApprovalStatusCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("apv_sts_cd");

                    b.Property<DateTime>("RecordEffectiveStartDate")
                        .HasColumnType("Date")
                        .HasColumnName("rec_eff_stt_dt");

                    b.Property<decimal>("DeficitRatingMinimumWeight")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("dfw_rtg_min_wgt_qy");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.Property<DateTime>("RecordEffectiveEndDate")
                        .HasColumnType("Date")
                        .HasColumnName("rec_eff_end_dt");

                    b.Property<string>("WeightDataPpnIndicator")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char")
                        .HasColumnName("wgt_dat_ppn_ir");

                    b.HasKey("Country", "WeightMeasurementUnitType", "ApprovalStatusCode", "RecordEffectiveStartDate");

                    b.ToTable("tdfwthr");
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.DeficitWeightThresholdStaging", b =>
                {
                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("cny_cd");

                    b.Property<string>("WeightMeasurementUnitType")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("wgt_ms_unt_typ_cd");

                    b.Property<string>("ApprovalStatusCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("apv_sts_cd");

                    b.Property<DateTime>("RecordEffectiveStartDate")
                        .HasColumnType("Date")
                        .HasColumnName("rec_eff_stt_dt");

                    b.Property<decimal>("DeficitRatingMinimumWeight")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("dfw_rtg_min_wgt_qy");

                    b.Property<short>("IsCompletedIndicator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("is_completed_ir");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.Property<DateTime>("RecordEffectiveEndDate")
                        .HasColumnType("Date")
                        .HasColumnName("rec_eff_end_dt");

                    b.Property<string>("WeightDataPpnIndicator")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char")
                        .HasColumnName("wgt_dat_ppn_ir");

                    b.HasKey("Country", "WeightMeasurementUnitType", "ApprovalStatusCode", "RecordEffectiveStartDate");

                    b.ToTable("tdfwthr_stg", (string)null);
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.DestinationZipSvcAsyValidation", b =>
                {
                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("cny_cd");

                    b.Property<string>("DestinationPostalCode")
                        .HasMaxLength(9)
                        .HasColumnType("char")
                        .HasColumnName("dtn_psl_cd");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("Date")
                        .HasColumnName("rec_eff_stt_dt");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("Date")
                        .HasColumnName("rec_eff_end_dt");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.Property<decimal>("PercentProgramPremiumValue")
                        .HasColumnType("decimal(16,0)")
                        .HasColumnName("prc_pgm_prm_vlu_te");

                    b.HasKey("Country", "DestinationPostalCode", "EffectiveDate");

                    b.ToTable("tdstsvp", (string)null);
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.DestinationZipSvcAsyValidationStaging", b =>
                {
                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("cny_cd");

                    b.Property<string>("DestinationPostalCode")
                        .HasMaxLength(9)
                        .HasColumnType("char")
                        .HasColumnName("dtn_psl_cd");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("Date")
                        .HasColumnName("rec_eff_stt_dt");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("Date")
                        .HasColumnName("rec_eff_end_dt");

                    b.Property<short>("IsCompletedIndicator")
                        .HasColumnType("smallint")
                        .HasColumnName("is_completed_ir");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.Property<decimal>("PercentProgramPremiumValue")
                        .HasColumnType("decimal(16,0)")
                        .HasColumnName("prc_pgm_prm_vlu_te");

                    b.HasKey("Country", "DestinationPostalCode", "EffectiveDate");

                    b.ToTable("tdstsvp_stg", (string)null);
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.DataLoadDetail", b =>
                {
                    b.HasOne("UPS.WWRR.Data.Models.DataLoad", "DataLoad")
                        .WithMany("Details")
                        .HasForeignKey("DataLoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataLoad");
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.DataLoadError", b =>
                {
                    b.HasOne("UPS.WWRR.Data.Models.DataLoadDetail", "DataLoadDetail")
                        .WithMany("Errors")
                        .HasForeignKey("DataLoadDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataLoadDetail");
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.DataLoadException", b =>
                {
                    b.HasOne("UPS.WWRR.Data.Models.DataLoadDetail", "DataLoadDetail")
                        .WithMany("Exceptions")
                        .HasForeignKey("DataLoadDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataLoadDetail");
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.DataLoad", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.DataLoadDetail", b =>
                {
                    b.Navigation("Errors");

                    b.Navigation("Exceptions");
                });
#pragma warning restore 612, 618
        }
    }
}
