// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UPS.WWRR.Data.Models;

#nullable disable

namespace UPS.WWRR.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251201123000_Script_AccessorialThreshold_Merge_SP")]
    partial class Script_AccessorialThreshold_Merge_SP
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
            // Script-only migration: no model changes. Keep in sync with DataContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
