// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UPS.WWRR.Data.Models;

#nullable disable

namespace UPS.WWRR.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251201121449_Add-TFPUTRH-Table")]
    partial class AddTFPUTRHTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UPS.WWRR.Data.Models.AccessorialThreshold", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("cny_cd");

                    b.Property<string>("AccessorialServiceTypeCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("asy_svc_typ_cd");

                    b.Property<string>("ApprovalStatusCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("apv_sts_cd");

                    b.Property<DateTime>("RecordEffectiveStartDate")
                        .HasColumnType("date")
                        .HasColumnName("rec_eff_stt_dt");

                    b.Property<int>("DailyThresholdQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("asy_dly_trh_qy");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.Property<DateTime>("RecordEffectiveEndDate")
                        .HasColumnType("date")
                        .HasColumnName("rec_eff_end_dt");

                    b.Property<int>("WeeklyThresholdQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("asy_wky_trh_qy");

                    b.HasKey("CountryCode", "AccessorialServiceTypeCode", "ApprovalStatusCode", "RecordEffectiveStartDate");

                    b.ToTable("tfputrh");
                });

            modelBuilder.Entity("UPS.WWRR.Data.Models.AccessorialThresholdStaging", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("cny_cd");

                    b.Property<string>("AccessorialServiceTypeCode")
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("asy_svc_typ_cd");

                    b.Property<string>("ApprovalStatusCode")
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("apv_sts_cd");

                    b.Property<DateTime>("RecordEffectiveStartDate")
                        .HasColumnType("date")
                        .HasColumnName("rec_eff_stt_dt");

                    b.Property<int>("DailyThresholdQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("asy_dly_trh_qy");

                    b.Property<short>("IsCompletedIndicator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("is_completed_ir");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.Property<DateTime>("RecordEffectiveEndDate")
                        .HasColumnType("date")
                        .HasColumnName("rec_eff_end_dt");

                    b.Property<int>("WeeklyThresholdQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("asy_wky_trh_qy");

                    b.HasKey("CountryCode", "AccessorialServiceTypeCode", "ApprovalStatusCode", "RecordEffectiveStartDate");

                    b.ToTable("tfputrh_stg", (string)null);
                });

#pragma warning restore 612, 618
        }
    }
}
