// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UPS.WWRR.Data.Models;

#nullable disable

namespace UPS.WWRR.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260307100000_Update_taltccy_usr_nr_nullable")]
    partial class Update_taltccy_usr_nr_nullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("a886aa_ao")
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UPS.WWRR.Data.Models.AlternateCurrency", b =>
                {
                    b.Property<string>("CurrencyFrom")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("cnv_fr_ccy_cd");

                    b.Property<string>("CurrencyTo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .HasColumnName("cnv_to_ccy_cd");

                    b.Property<decimal>("DomesticCalculationQuantity")
                        .HasColumnType("decimal(9,0)")
                        .HasColumnName("alt_ccy_dmc_ccl_qy");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("Date")
                        .HasColumnName("alt_ccy_xch_stt_dt");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("Date")
                        .HasColumnName("alt_ccy_xch_end_dt");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(15,9)")
                        .HasColumnName("alt_ccy_xch_ra_qy");

                    b.Property<string>("ExportCountry")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char")
                        .HasColumnName("xpt_cny_cd");

                    b.Property<string>("LoadReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("load_ref_te");

                    b.Property<decimal>("OriginalQuantity")
                        .HasColumnType("decimal(15,9)")
                        .HasColumnName("alt_ccy_xch_or_qy");

                    b.Property<decimal>("RoundedDomesticQuantity")
                        .HasColumnType("decimal(9,0)")
                        .HasColumnName("alt_ccy_rou_dmc_qy");

                    b.Property<string>("UserNumber")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("char")
                        .HasDefaultValue("")
                        .HasColumnName("usr_nr");

                    b.ToTable("taltccy", "a886aa_ao");
                });
#pragma warning restore 612, 618
        }
    }
}
