FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN addgroup --system appgroup && \
    adduser --system appuser --ingroup appgroup

RUN apt-get update && \
    apt-get install -y curl openjdk-17-jre && \
    rm -rf /var/lib/apt/lists/*

RUN dotnet tool install --global dotnet-sonarscanner

ENV PATH="/home/appuser/.dotnet/tools:/usr/local/bin:/usr/bin:/bin"

USER appuser

WORKDIR /app