apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.monitoring.tlsSecret }}
  namespace: istio-system
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.monitoring.tlsCrt }}
  tls.key: {{ .Values.monitoring.tlsKey }}