apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ups-wwrr-batch
  namespace: argocd-dev
  annotations:
    argocd-image-updater.argoproj.io/image-list: wwrr= us-central1-docker.pkg.dev/gcp-cti-wwrr-dev/wwrr-dev-docker-repo/ups-wwrr-batch
    argocd-image-updater.argoproj.io/wwrr.allow-tags: latest
    argocd-image-updater.argoproj.io/wwrr.force-update: "true"
spec:
  project: default
  source:
    repoURL: https://dev.azure.com/UPSProd4/P4AG_MARKETING_APPS/_git/wwrr-mod-app-data-load
    targetRevision: main
    path: manifests/ups-wwrr-batch
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true