replicaCount: 1

image:
  repository: ""
  tag: latest
  pullPolicy: Always

serviceAccount:
  create: false
  annotations: {}
  name: ups-wwrr-batch

env:
  GOOGLE_CLOUD_STORAGE_BUCKET_NAME: ""
  LOAD_INTERVAL_MINUTES: ""
  TABLE_NAME: ""
  BATCH_SIZE: ""
  ASPNETCORE_ENVIRONMENT: ""
  ALLOYDB_CONNECTION: ""
  BatchLoad_ChunkSize: ""
  BatchLoad_Delimiter: ""
  BatchLoad_HasHeader: ""
  EnableIAMTokenAuth: ""
  GCS_DOWNLOAD_CHUNK_SIZE: ""
  TVASYLN_USE_BATCH_MERGE: ""
  TRASTD_USE_BATCH_MERGE: ""
  TSUBCHG_USE_BATCH_MERGE: ""

ALLOYDB_INSTANCE: ""
ALLOYDB_HOST_ALIAS_IP: ""
ALLOYDB_HOST_ALIAS_NAME: ""

resources:
  requests:
    memory: "3Gi"
    cpu: "3"
  limits:
    memory: "4Gi"
    cpu: "4"

alloydbProxy:
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

nodeSelector: {}
tolerations: []
affinity: {}