replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/gcp-cti-wwrr-dev/wwrr-dev-docker-repo/ups-wwrr-batch
  tag: latest
  pullPolicy: Always

serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: terraform-infra@gcp-cti-wwrr-dev.iam.gserviceaccount.com
  name: ups-wwrr-batch

env:
  GOOGLE_CLOUD_STORAGE_BUCKET_NAME: ""
  LOAD_INTERVAL_MINUTES: ""
  TABLE_NAME: ""
  BATCH_SIZE: ""
  ASPNETCORE_ENVIRONMENT: ""
  ALLOYDB_CONNECTION: "Host=127.0.0.1;Port=5432;Database=dev_u7x_001;Username='wwrr-mod-app-alloydb@gcp-cti-wwrr-dev.iam';Search Path=a886aa_ao;SslMode=Require"
  BatchLoad_ChunkSize: ""
  BatchLoad_Delimiter: ""
  BatchLoad_HasHeader: ""

alloydbAuthProxy:
  enabled: true
  image: gcr.io/alloydb-auth-proxy/alloydb-auth-proxy:latest
  port: 5432
  address: 127.0.0.1
  instance: gcp-cti-wwrr-dev:us-central1:wwrr-dev-alloydb

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1"

nodeSelector: {}
tolerations: []
affinity: {}