<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Google.Cloud.Functions.Hosting" Version="3.0.1" />
    <PackageReference Include="Google.Cloud.PubSub.V1" Version="3.22.0" />
    <PackageReference Include="Google.Cloud.Storage.V1" Version="4.13.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
      <ProjectReference Include="..\UPS.WWRR.Data\UPS.WWRR.Data.csproj" />
  </ItemGroup>

</Project>
