apiVersion: v1
kind: Secret
metadata:
  name: kiali-oauth-secret
  namespace: istio-system
type: Opaque
stringData:
  client_id: "{{ .Values.kiali.clientId }}"
  client_secret: "{{ .Values.kiali.clientSecret }}"